# Generated by Django 3.2.11 on 2022-04-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20220421_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ToDo', to='todo.project', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(blank=True, to='todo.ProjectUser', verbose_name='Пользователи'),
        ),
    ]
